// <auto-generated />
namespace SurveyApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Identityuseranduserprofilearemixedtogether : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Identityuseranduserprofilearemixedtogether));
        
        string IMigrationMetadata.Id
        {
            get { return "201709261052570_Identity user and user profile are mixed together"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
