// <auto-generated />
namespace SurveyApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TempId1WasRenamedToNameInUserProfileTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TempId1WasRenamedToNameInUserProfileTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201709261301559_TempId1WasRenamedToNameInUserProfileTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
